server:
    port: 8080

spring:
    datasource:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite.db

    jpa:
        database-platform: org.hibernate.community.dialect.SQLiteDialect
        hibernate:
            ddl-auto: update
        show-sql: true

management:
    endpoints:
        web:
            exposure:
                include: '*'
        health:
            show-details: always
    info:
        java:
            enabled: true
        os:
            enabled: true
        env:
            enabled: true


spring.boot.admin.client:
    url: http://localhost:8080